### ISSUE TITLE
#02 죽은 몬스터를 공격했을 때 다른 몬스터를 잡을 것으로 처리됩니다.

### ISSUE THREAD

**Issue by rlarhdal** [choiyunhwa/SpartaDungeon#5]
예시 상황
[대포미니언, 드래곤]
죽은 대포미니언을 선택하니 데미지가 들어가고 죽인 count로 넘어가서 드래곤은 스킵된 채 스테이지가 끝납니다.

**Comment by choiyunhwa** [comment]
죽은 몬스터인지 아닌지 확인 후 선택지가 넘어가도록 수정하였습니다.

**Comment by choiyunhwa** [comment]
![화면 캡처 2024-05-03 210221](https://github.com/choiyunhwa/SpartaDungeon/assets/101029607/6baa40bc-d5e9-4257-818c-056fd97a489c)
